import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import { token } from "@/libs/auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Expo Hub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const user = token();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {user ? (
          <Navbar user={{ name: user?.firstName, role: user?.role?.name }} />
        ) : (
          <Navbar user={null} />
        )}
        {children}
        <Footer />
      </body>
    </html>
  );
}
